// dsh-plugin-chat-rollback — 快照目录生命周期 域。
// 从原单文件 index.js 拆出：回滚/fork 子会话的快照硬链接继承
// （inheritSnapshots）与统一快照清理（pruneSnapshots：archived / non-standard /
// orphan 三类目录回收，含内容守卫与孤儿缓冲期）。写侧（onSessionEvent）在
// index.js，回收入口为 rollback 惰性清理、周期定时器与手动清理端点。
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import { fsTargetExists } from './workspace.js';
/** Link the source session's turn snapshots up to maxTurn into the child
 * session's snapshot dir, so a further rollback inside the child to a seeded
 * message (turn T <= maxTurn-1) still finds turn-(T+1). Hardlinks share blocks
 * (zero-copy); falls back to copyFile across filesystems. Idempotent: a
 * missing source dir or an already-present target is a no-op. */
async function inheritSnapshots(env, sourceId, childId, maxTurn) {
  const sourceDir = join(env.snapRoot, sourceId);
  const childDir = join(env.snapRoot, childId);
  let entries;
  try {
    entries = await fs.readdir(sourceDir);
  } catch {
    return { inherited: 0 };
  }
  let inherited = 0;
  try {
    await fs.mkdir(childDir, { recursive: true });
    for (const entry of entries) {
      // Inherit the full-tree snapshot and its start manifest (state AFTER the
      // previous turn). End manifests (turn-N.end.files.json) are session-local
      // "last write" records regenerated by each session's own turn/end, so they
      // are deliberately excluded here.
      const m = /^turn-(\d+)\.(?:tar\.zst|files\.json)$/.exec(entry);
      if (m === null) continue;
      const num = Number(m[1]);
      if (!Number.isInteger(num) || num < 1 || num > maxTurn) continue;
      const dst = join(childDir, entry);
      if (await fsTargetExists(dst)) continue;
      const src = join(sourceDir, entry);
      try {
        await fs.link(src, dst);
      } catch {
        await fs.copyFile(src, dst);
      }
      inherited += 1;
    }
    return { inherited };
  } catch (error) {
    return { inherited, error: String(error?.message ?? error) };
  }
}

/** 孤儿回收缓冲：session- 前缀但 registry 无记录的目录，需停止活动超过该时长
 * 才回收——给「会话刚创建、workspace attach 尚未完成」的竞态留缓冲，避免误删
 * 活跃会话的快照。 */
const ORPHAN_GRACE_MS = 24 * 60 * 60 * 1000;

/** 快照根下的顶层目录（跳过符号链接与文件）。 */
async function listSnapshotDirs(snapRoot) {
  let entries;
  try {
    entries = await fs.readdir(snapRoot);
  } catch {
    return [];
  }
  const dirs = [];
  for (const entry of entries) {
    try {
      const st = await fs.lstat(join(snapRoot, entry));
      if (st.isDirectory() && !st.isSymbolicLink()) dirs.push(entry);
    } catch {}
  }
  return dirs;
}

/** 目录内容是否像本插件的快照目录（含 turn-N.tar.zst / files.json / recovery-*）。
 * 回收非标准前缀目录前用此守卫：即使 snapshotDir 被指向别的目录树，也只回收
 * 确实由本插件产出的子目录，绝不碰无关用户数据。 */
async function looksLikeSnapshotDir(dir) {
  try {
    const entries = await fs.readdir(dir);
    return entries.some((entry) => /^turn-\d+\.(?:tar\.zst|files\.json)$/.test(entry) || entry.startsWith('recovery-'));
  } catch {
    return false;
  }
}

/** 当前"活着"的会话 id：sessions registry（所有 live 会话）+ workspace 记账的
 * sessionIds（含归档后保留席位但 sessions 里已下线的）。孤儿判定基于该集合。 */
function liveSessionIds(env) {
  const ids = new Set();
  try {
    for (const session of env.ctx.sessions?.list?.() ?? []) {
      if (session && typeof session.id === 'string') ids.add(session.id);
    }
  } catch {}
  try {
    for (const workspace of env.ctx.workspaceRegistry?.list?.() ?? []) {
      for (const id of workspace?.sessionIds ?? []) ids.add(id);
    }
  } catch {}
  return ids;
}

/** 统一快照清理。回收三类目录：
 *  - archived：已归档会话（回滚或手动归档）——清理即回收（后代硬链接除外，
 *    空间随链路末端清理释放，属硬链接的正常语义）；
 *  - non-standard：非 session- 前缀的目录（arena 对局会话、旧格式 UUID）——
 *    写侧已停（见 onSessionEvent），无 rollback 语义，存量一次性回收；
 *  - orphan：session- 前缀但 sessions/workspace 均无记录、且停止活动超过
 *    ORPHAN_GRACE_MS（会话已删除或从未注册）——避免 attach 竞态误删。
 * 非 archived 目录回收前都过 looksLikeSnapshotDir 守卫，防 snapshotDir 被指向
 * 无关目录树时误删用户数据。
 * Runs lazily from handleRollback, on a periodic timer (apply), and via
 * POST /chat-rollback/prune-archived. */
async function pruneSnapshots(env, sessionIdHint, skipId) {
  try {
    const archived = new Set(env.ctx.workspaceRegistry?.archivedSessionIds ?? []);
    if (sessionIdHint !== undefined && !archived.has(sessionIdHint)) return { ok: true, pruned: [], orphaned: [] };
    const live = liveSessionIds(env);
    const dirs = await listSnapshotDirs(env.snapRoot);
    const pruned = [];
    const orphaned = [];
    const now = Date.now();
    for (const entry of dirs) {
      if (sessionIdHint !== undefined && entry !== sessionIdHint) continue;
      // skipId：回滚中正被继承的源会话目录不在此次清理范围（见 handleRollback
      // 的惰性清理调用——它异步执行，可能与快照硬链接继承并发）。
      if (skipId !== undefined && entry === skipId) continue;
      let reason = null;
      if (archived.has(entry)) {
        reason = 'archived';
      } else if (!entry.startsWith('session-')) {
        // 非标准前缀目录：确认是本插件产物（防误删），且写侧已停不再增长
        if (await looksLikeSnapshotDir(join(env.snapRoot, entry))) reason = 'non-standard';
      } else if (!live.has(entry)) {
        // session- 前缀孤儿：registry 无记录，且停止活动超过缓冲期
        try {
          const st = await fs.stat(join(env.snapRoot, entry));
          if (now - st.mtimeMs > ORPHAN_GRACE_MS && (await looksLikeSnapshotDir(join(env.snapRoot, entry)))) reason = 'orphan';
        } catch {}
      }
      if (reason === null) continue;
      try {
        await fs.rm(join(env.snapRoot, entry), { recursive: true, force: true });
        (reason === 'orphan' ? orphaned : pruned).push(entry);
      } catch (error) {
        env.ctx.logger?.warn?.('chat-rollback: prune failed for ' + entry + ': ' + String(error));
      }
    }
    return { ok: true, pruned, orphaned };
  } catch (error) {
    return { ok: false, message: String(error?.message ?? error) };
  }
}


export { inheritSnapshots, pruneSnapshots };
